# Generated by Django 6.0.6 on 2026-06-19 18:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_type', models.CharField(choices=[('FAMILY', 'Family Member'), ('FRIEND', 'Friend'), ('EMERGENCY', 'Emergency Contact')], max_length=12)),
                ('relationship', models.CharField(blank=True, choices=[('PARENT', 'Parent'), ('SPOUSE', 'Spouse'), ('CHILD', 'Child'), ('SIBLING', 'Sibling'), ('GUARDIAN', 'Guardian'), ('OTHER', 'Other')], max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_primary_emergency', models.BooleanField(default=False)),
                ('is_secondary_emergency', models.BooleanField(default=False)),
                ('notify_on_journey', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['contact_type', 'name'],
                'indexes': [models.Index(fields=['owner', 'contact_type'], name='safety_trus_owner_i_d35fc0_idx')],
            },
        ),
    ]
