# Generated by Django 6.0.6 on 2026-06-19 20:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journeys', '0002_trackinglink_journeyshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('IMPACT', 'Impact Detected'), ('ROLLOVER', 'Rollover Detected'), ('SUDDEN_STOP', 'Sudden Stop Detected'), ('POSSIBLE_ACCIDENT', 'Possible Accident')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('confirmation_status', models.CharField(choices=[('PENDING', 'Awaiting User Response'), ('SAFE', 'User Confirmed Safe'), ('NEEDS_HELP', 'User Requested Help'), ('TIMED_OUT', 'No Response — Auto-Escalated'), ('ESCALATED', 'Escalated to iSafePass')], default='PENDING', max_length=12)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('acceleration_magnitude', models.FloatField(blank=True, null=True)),
                ('speed_before', models.FloatField(blank=True, null=True)),
                ('speed_after', models.FloatField(blank=True, null=True)),
                ('tilt_angle', models.FloatField(blank=True, null=True)),
                ('rotation_rate', models.FloatField(blank=True, null=True)),
                ('raw_sensor', models.JSONField(blank=True, default=dict)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('countdown_task_id', models.CharField(blank=True, max_length=256)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accident_events', to='journeys.journey')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyEscalation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('escalation_type', models.CharField(choices=[('SOS', 'SOS Request'), ('ACCIDENT_INCIDENT', 'Accident Incident'), ('PANIC', 'Panic Button')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], default='PENDING', max_length=10)),
                ('isafepass_incident_id', models.CharField(blank=True, max_length=256)),
                ('isafepass_sos_id', models.CharField(blank=True, max_length=256)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('accident_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations', to='accident_detection.accidentevent')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_escalations', to='journeys.journey')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('success', models.BooleanField(default=False)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('escalation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='accident_detection.emergencyescalation')),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='SOSRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sos_type', models.CharField(choices=[('PASSENGER_SOS', 'Passenger SOS'), ('DRIVER_PANIC', 'Driver/Rider Panic Button')], max_length=16)),
                ('status', models.CharField(choices=[('TRIGGERED', 'Triggered'), ('DELIVERED', 'Delivered to iSafePass'), ('FAILED', 'Delivery Failed'), ('RETRYING', 'Retrying Delivery')], default='TRIGGERED', max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('isafepass_sos_id', models.CharField(blank=True, max_length=256)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_requests', to='journeys.journey')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_triggers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.AddField(
            model_name='emergencyescalation',
            name='sos_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations', to='accident_detection.sosrequest'),
        ),
        migrations.AddIndex(
            model_name='accidentevent',
            index=models.Index(fields=['journey', '-detected_at'], name='accident_de_journey_19ddc7_idx'),
        ),
        migrations.AddIndex(
            model_name='sosrequest',
            index=models.Index(fields=['journey', '-triggered_at'], name='accident_de_journey_4ef7e8_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyescalation',
            index=models.Index(fields=['journey', '-created_at'], name='accident_de_journey_b7e034_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyescalation',
            index=models.Index(fields=['status', 'next_retry_at'], name='accident_de_status_f525ff_idx'),
        ),
    ]
