# Generated by Django 6.0.6 on 2026-06-19 10:40

import common.models
import common.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('doc_type', models.CharField(choices=[('NATIONAL_ID', 'National Id'), ('VOTER_CARD', 'Voter Card'), ('PASSPORT', 'Passport'), ('DRIVER_LICENSE', 'Driver License'), ('PASSPORT_PHOTO', 'Passport Photo'), ('SELFIE', 'Selfie'), ('VEHICLE_REGISTRATION', 'Vehicle Registration'), ('PROOF_OF_OWNERSHIP', 'Proof Of Ownership'), ('INSPECTION_CERTIFICATE', 'Inspection Certificate'), ('INSURANCE', 'Insurance'), ('CAC_CERTIFICATE', 'Cac Certificate'), ('PROOF_OF_ADDRESS', 'Proof Of Address'), ('REP_ID', 'Rep Id')], max_length=32)),
                ('file', models.FileField(storage=common.storage.PrivateMediaStorage(), upload_to=common.models._document_upload_path)),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='common_veri_content_4b522a_idx'), models.Index(fields=['owner', 'doc_type'], name='common_veri_owner_i_b466fe_idx'), models.Index(fields=['expiry_date'], name='common_veri_expiry__0badef_idx')],
            },
        ),
    ]
