# Generated by Django 6.0.6 on 2026-06-19 20:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driver_participant_type'),
        ('operators', '0001_initial'),
        ('vehicles', '0002_vehicle_owner_vehicleverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('branch_type', models.CharField(choices=[('HQ', 'Headquarters'), ('REGIONAL', 'Regional Office'), ('LOCAL', 'Local Branch')], default='LOCAL', max_length=16)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='operators.branch')),
            ],
            options={
                'ordering': ['branch_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TransportOperator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=100)),
                ('business_type', models.CharField(choices=[('BUS_COMPANY', 'Bus Company'), ('TAXI', 'Taxi Operator'), ('KEKE', 'Keke Association'), ('OKADA', 'Okada Association'), ('SCHOOL_TRANSPORT', 'School Transport'), ('CORPORATE_SHUTTLE', 'Corporate Shuttle'), ('DELIVERY', 'Delivery Company'), ('LOGISTICS', 'Logistics Operator'), ('GOVERNMENT_FLEET', 'Government Fleet')], max_length=32)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_address', models.TextField(blank=True)),
                ('fleet_safety_score', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_operators', to=settings.AUTH_USER_MODEL)),
                ('verification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_operator', to='operators.operatorverification')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperatorMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('FLEET_MANAGER', 'Fleet Manager'), ('SAFETY_MANAGER', 'Safety Manager'), ('OPERATIONS_MANAGER', 'Operations Manager'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='operators.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_memberships', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='operators.transportoperator')),
            ],
        ),
        migrations.CreateModel(
            name='FleetSafetyScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(default=0.0)),
                ('level', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='POOR', max_length=16)),
                ('incident_factor', models.FloatField(default=0.0)),
                ('deviation_factor', models.FloatField(default=0.0)),
                ('compliance_factor', models.FloatField(default=0.0)),
                ('performance_factor', models.FloatField(default=0.0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('operator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety_score', to='operators.transportoperator')),
            ],
        ),
        migrations.CreateModel(
            name='FleetParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participant_type', models.CharField(choices=[('DRIVER', 'Driver'), ('RIDER', 'Rider'), ('OPERATOR_PERSONNEL', 'Operator Personnel')], max_length=24)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=16)),
                ('suspension_reason', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_participants_added', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='operators.branch')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_assignments', to='drivers.driver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_assignments', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='operators.transportoperator')),
            ],
        ),
        migrations.CreateModel(
            name='FleetAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ASSIGNED', 'Assigned'), ('RETIRED', 'Retired'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=16)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_assets_added', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='operators.branch')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_assignments', to='vehicles.vehicle')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='operators.transportoperator')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='operators.transportoperator'),
        ),
        migrations.CreateModel(
            name='ParticipantAssetAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_assignments', to='operators.fleetasset')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_asset_assignments', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_assignments', to='operators.fleetparticipant')),
            ],
            options={
                'indexes': [models.Index(fields=['participant', 'is_active'], name='operators_p_partici_23907d_idx'), models.Index(fields=['asset', 'is_active'], name='operators_p_asset_i_cd1dab_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='transportoperator',
            index=models.Index(fields=['owner'], name='operators_t_owner_i_336874_idx'),
        ),
        migrations.AddIndex(
            model_name='transportoperator',
            index=models.Index(fields=['business_type', 'is_active'], name='operators_t_busines_fd16e6_idx'),
        ),
        migrations.AddIndex(
            model_name='operatormembership',
            index=models.Index(fields=['operator', 'role', 'is_active'], name='operators_o_operato_45b5a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='operatormembership',
            unique_together={('operator', 'user')},
        ),
        migrations.AddIndex(
            model_name='fleetparticipant',
            index=models.Index(fields=['operator', 'status'], name='operators_f_operato_6b6f51_idx'),
        ),
        migrations.AddIndex(
            model_name='fleetparticipant',
            index=models.Index(fields=['operator', 'participant_type', 'status'], name='operators_f_operato_7e1745_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fleetparticipant',
            unique_together={('operator', 'user')},
        ),
        migrations.AddIndex(
            model_name='fleetasset',
            index=models.Index(fields=['operator', 'status'], name='operators_f_operato_66c574_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fleetasset',
            unique_together={('operator', 'vehicle')},
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('operator', 'name')},
        ),
    ]
