# Generated by Django 6.0.6 on 2026-06-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driververification'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='participant_type',
            field=models.CharField(blank=True, choices=[('TAXI_DRIVER', 'Taxi Driver'), ('BUS_DRIVER', 'Bus Driver'), ('KEKE_RIDER', 'Keke Rider'), ('OKADA_RIDER', 'Okada Rider'), ('SHUTTLE_DRIVER', 'Shuttle Driver'), ('DELIVERY_RIDER', 'Delivery Rider'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
