# Generated by Django 6.0.6 on 2026-06-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trust_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_level',
            field=models.IntegerField(choices=[(0, 'Unverified'), (1, 'Basic (phone + email)'), (2, 'Identity Verified'), (3, 'Verified Driver')], default=0),
        ),
    ]
