# Generated by Django 6.0.6 on 2026-06-19 18:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journeys', '0002_trackinglink_journeyshare'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyRisk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(default=0.0)),
                ('level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=10)),
                ('factors', models.JSONField(blank=True, default=dict)),
                ('incident_created', models.BooleanField(default=False)),
                ('incident_id', models.CharField(blank=True, max_length=256)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('journey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk', to='journeys.journey')),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='PlannedRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('waypoints', models.JSONField(blank=True, default=list)),
                ('expected_duration_s', models.IntegerField(blank=True, null=True)),
                ('expected_distance_m', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEVIATED', 'Deviated'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planned_route', to='journeys.journey')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JourneyWarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('warning_type', models.CharField(choices=[('ROUTE_DEVIATION', 'Route Deviation'), ('WRONG_DIRECTION', 'Wrong Direction'), ('UNEXPECTED_STOP', 'Unexpected Stop'), ('DANGEROUS_AREA', 'Dangerous Area'), ('HIGH_RISK', 'High Risk Score'), ('INCIDENT_RECOMMENDED', 'Incident Recommended'), ('INCIDENT_CREATED', 'Incident Created in iSafePass')], max_length=24)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('DANGER', 'Danger'), ('CRITICAL', 'Critical')], default='WARNING', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='journeys.journey')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['journey', '-created_at'], name='route_intel_journey_77bf47_idx')],
            },
        ),
        migrations.CreateModel(
            name='RouteDeviation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deviation_type', models.CharField(choices=[('ROUTE_DEVIATION', 'Route Deviation'), ('WRONG_DIRECTION', 'Wrong Direction'), ('UNAUTHORIZED_CHANGE', 'Unauthorized Route Change'), ('EXCESSIVE_DETOUR', 'Excessive Detour')], max_length=24)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('distance_from_route_m', models.FloatField(blank=True, null=True)),
                ('heading_error_deg', models.FloatField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviations', to='journeys.journey')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['journey', '-timestamp'], name='route_intel_journey_247cf1_idx')],
            },
        ),
        migrations.CreateModel(
            name='UnexpectedStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_s', models.IntegerField(blank=True, null=True)),
                ('is_unsafe_area', models.BooleanField(default=False)),
                ('area_safety_score', models.FloatField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unexpected_stops', to='journeys.journey')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['journey', '-started_at'], name='route_intel_journey_871d53_idx')],
            },
        ),
    ]
