# Generated by Django 6.0.6 on 2026-06-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('getting_started', 'Getting Started'), ('rides', 'Rides & Safety'), ('contacts', 'Trusted Contacts'), ('account', 'Account & Profile'), ('technical', 'Technical Issues'), ('other', 'Other')], default='other', max_length=30)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first within a category.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'order', 'created_at'],
            },
        ),
    ]
