# Generated by Django 6.0.6 on 2026-06-19 17:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0003_driver_participant_type'),
        ('qr_codes', '0001_initial'),
        ('vehicles', '0002_vehicle_owner_vehicleverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('VERIFIED', 'Verified'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('INCIDENT', 'Incident'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved')], default='CREATED', max_length=12)),
                ('origin_lat', models.FloatField(blank=True, null=True)),
                ('origin_lng', models.FloatField(blank=True, null=True)),
                ('origin_address', models.CharField(blank=True, max_length=512)),
                ('destination_lat', models.FloatField(blank=True, null=True)),
                ('destination_lng', models.FloatField(blank=True, null=True)),
                ('destination_address', models.CharField(blank=True, max_length=512)),
                ('estimated_distance_m', models.FloatField(blank=True, null=True)),
                ('estimated_duration_s', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('pause_reason', models.CharField(blank=True, max_length=256)),
                ('cancellation_reason', models.CharField(blank=True, max_length=256)),
                ('asset_qr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_journeys', to='qr_codes.qrcode')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='drivers.driver')),
                ('participant_qr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_journeys', to='qr_codes.qrcode')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys_as_passenger', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JourneyEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('journey.created', 'Journey Created'), ('journey.started', 'Journey Started'), ('journey.paused', 'Journey Paused'), ('journey.resumed', 'Journey Resumed'), ('journey.completed', 'Journey Completed'), ('journey.cancelled', 'Journey Cancelled'), ('destination.set', 'Destination Set'), ('route.updated', 'Route Updated'), ('alert', 'Alert'), ('participant.connected', 'Participant Connected'), ('participant.disconnected', 'Participant Disconnected'), ('passenger.connected', 'Passenger Connected'), ('passenger.disconnected', 'Passenger Disconnected'), ('location.updated', 'Location Updated'), ('incident', 'Incident'), ('escalated', 'Escalated'), ('resolved', 'Resolved')], max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journey_events', to=settings.AUTH_USER_MODEL)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='journeys.journey')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='JourneyLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('client_timestamp', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='journeys.journey')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['passenger', '-created_at'], name='journeys_jo_passeng_45e2bd_idx'),
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['driver', '-created_at'], name='journeys_jo_driver__af7244_idx'),
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['status'], name='journeys_jo_status_9cccad_idx'),
        ),
        migrations.AddIndex(
            model_name='journeyevent',
            index=models.Index(fields=['journey', '-timestamp'], name='journeys_jo_journey_64c72d_idx'),
        ),
        migrations.AddIndex(
            model_name='journeyevent',
            index=models.Index(fields=['event_type'], name='journeys_jo_event_t_7a5cda_idx'),
        ),
        migrations.AddIndex(
            model_name='journeylocation',
            index=models.Index(fields=['journey', '-timestamp'], name='journeys_jo_journey_04d629_idx'),
        ),
    ]
