# Generated by Django 6.0.6 on 2026-06-19 18:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0001_initial'),
        ('safety', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=512, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tracking_links', to=settings.AUTH_USER_MODEL)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_links', to='journeys.journey')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JourneyShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('privacy', models.JSONField(blank=True, default=dict, help_text='e.g. {"show_location": true, "show_participant": true, "show_asset": true}')),
                ('active', models.BooleanField(default=True)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('unshared_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_shares', to='safety.trustedcontact')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='journeys.journey')),
            ],
            options={
                'ordering': ['-shared_at'],
                'unique_together': {('journey', 'contact')},
            },
        ),
    ]
