# Generated by Django 6.0.6 on 2026-06-22 21:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0003_journey_group_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneySensorData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acceleration_x', models.FloatField()),
                ('acceleration_y', models.FloatField()),
                ('acceleration_z', models.FloatField()),
                ('acceleration_magnitude', models.FloatField()),
                ('speed', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='journeys.journey')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['journey', '-timestamp'], name='journeys_jo_journey_201275_idx')],
            },
        ),
    ]
