# Generated by Django 6.0.6 on 2026-06-19 16:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('PARTICIPANT', 'Participant'), ('ASSET', 'Asset')], max_length=16)),
                ('object_id', models.CharField(max_length=64)),
                ('token', models.CharField(max_length=1024, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=10)),
                ('generation', models.PositiveIntegerField(default=1)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_qr_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='QRScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_tried', models.CharField(max_length=1024)),
                ('result', models.CharField(choices=[('VALID', 'Valid'), ('INVALID_TOKEN', 'Invalid Token'), ('REVOKED', 'Revoked'), ('SUSPENDED', 'Suspended'), ('INELIGIBLE', 'Ineligible')], max_length=16)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='qr_codes.qrcode')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['content_type', 'object_id', 'status'], name='qr_codes_qr_content_814db9_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['entity_type', 'status'], name='qr_codes_qr_entity__f1b098_idx'),
        ),
        migrations.AddIndex(
            model_name='qrscan',
            index=models.Index(fields=['qr_code', '-scanned_at'], name='qr_codes_qr_qr_code_caeea9_idx'),
        ),
        migrations.AddIndex(
            model_name='qrscan',
            index=models.Index(fields=['scanned_by', '-scanned_at'], name='qr_codes_qr_scanned_3174cc_idx'),
        ),
        migrations.AddIndex(
            model_name='qrscan',
            index=models.Index(fields=['result', '-scanned_at'], name='qr_codes_qr_result_6545c6_idx'),
        ),
    ]
