# Generated by Django 6.0.6 on 2026-06-19 18:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journeys', '0002_trackinglink_journeyshare'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneySubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('isafepass_subscription_id', models.CharField(blank=True, max_length=256)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('journey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='isafepass_subscription', to='journeys.journey')),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
