# Generated by Django 6.0.6 on 2026-06-20 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('KYC_UPDATE', 'Kyc Update'), ('REVERIFICATION', 'Reverification'), ('RIDE', 'Ride'), ('SOS', 'Sos'), ('VERIFICATION', 'Verification'), ('NEWS', 'News'), ('GENERAL', 'General')], default='GENERAL', max_length=20),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_alerts', models.BooleanField(default=True)),
                ('sos_alerts', models.BooleanField(default=True)),
                ('verification_alerts', models.BooleanField(default=True)),
                ('news_alerts', models.BooleanField(default=False)),
                ('push_token', models.CharField(blank=True, max_length=512)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
